### ISSUE TITLE
H5Fopen failed during fast_check

### ISSUE THREAD

**Issue by happysky19** [nasa/RtRetrievalFramework#3]
Hi,

I got following error message when I run fast_check 

Running 417 test cases...

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**********unknown location(0): fatal error: in "forward_model_spectral_grid/low_resolution_grid": FullPhysics::Exception: Lua error: std::exception: 'While trying to open file '/groups/algorithm/l2_fp/absco/v3.3.0/lowres/co2_v3.3.0-lowres.hdf' a HDF 5 Exception thrown:
  H5Fopen failed'

lib/Interface/forward_model_spectral_grid_test.cc(68): last checkpoint: "low_resolution_grid" fixture entry.
unknown location(0): fatal error: in "forward_model_spectral_grid/high_resolution_grid": FullPhysics::Exception: Lua error: std::exception: 'While trying to open file '/groups/algorithm/l2_fp/absco/v3.3.0/lowres/co2_v3.3.0-lowres.hdf' a HDF 5 Exception thrown:
  H5Fopen failed'

What may cause this error?
Thanks,
Tianhao

**Comment by mikesmyth** [comment]
Tianhao,

The unit tests depend on a set of files referred to as ABSCO (see http://nasa.github.io/RtRetrievalFrameworkDoc/testing.html).  The normal production runs use version 5.0.0 of these files, but our unit tests use older versions of these tables. We just froze the unit tests at one point in development, we didn't want to update these each time we updated the ABSCO data. The unit tests depend on the older v3.3.0 version of these files.

The ABSCO tables are available at https://oco2.gesdisc.eosdis.nasa.gov/data/.A4ft5bK203Mc2nXI/OCO2_DATA, with the version v3.3.0 absco data one level lower at OCO2_L2_ABSCO.3.3.0/. Note that you will need to get a free Earthdata Login account, there are directions on the download page for getting this account.

When you have the data installed on your system, you'll need to specify the directory location you have using the "--with-absco" option in the configuration. We have this default to the directory /groups/algorithm/l2_fp/absco which is where the data is on our system, but presumably you'll have them installed in a different directory.  There is an assumed directory structure here, the V3.3.0 data should go in the directory $(abscodir)/v3.3.0/lowres.  The production v5.0.0 data should go into $(abscodir)/v5.0.0.

We don't include the ABSCO data with the source because of the size. Each of the data sets is about 2GB which is too large to put into github.

Mike

**Comment by happysky19** [comment]
Many thanks! I will try this. 

Also, seems the link for the ReFRACtor documentation  doesn't work now(https://github.jpl.nasa.gov/pages/refractor/documentation/). Could you update the link?

Thanks,
Tianhao

**Comment by mcduffie** [comment]
Use this link for the public ReFRACtor documentation:
https://refractor.github.io/documentation/
